import { useState } from 'react'
import { motion } from 'framer-motion'
import CountUp from 'react-countup'
import useEmblaCarousel from 'embla-carousel-react'
import { Menu, X, Store, Users, Truck, Sparkles, ArrowRight, Bot, ShieldCheck } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion'

const fade={hidden:{opacity:0,y:20},show:{opacity:1,y:0}}
const sections=[['Cómo funciona','#como-funciona'],['Para negocios','#negocios'],['Para revendedores','#revendedores'],['Beneficios','#beneficios'],['FAQ','#faq']]
export default function App(){const [open,setOpen]=useState(false); const [emblaRef]=useEmblaCarousel({loop:true});
return <div className='min-h-screen'>
<header className='sticky top-0 z-50 border-b border-slate-200/80 bg-white/90 backdrop-blur'><nav className='container flex h-16 items-center justify-between'><a href='#' className='text-xl font-bold'>Conecta <span className='text-blue-600'>Local</span></a><div className='hidden items-center gap-7 md:flex'>{sections.map(([n,h])=><a key={n} href={h} className='text-sm text-slate-600 hover:text-slate-900'>{n}</a>)}<Button>Registrarme</Button></div><button className='md:hidden' onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></nav>{open&&<div className='border-t bg-white p-4 md:hidden'>{sections.map(([n,h])=><a key={n} href={h} className='block py-2'>{n}</a>)}<Button className='mt-3 w-full'>Registrarme</Button></div>}</header>
<main>
<section className='container grid gap-10 py-20 md:grid-cols-2 md:py-28'><motion.div variants={fade} initial='hidden' animate='show'><p className='text-sm font-semibold text-blue-600'>Ecosistema híbrido para comercio local</p><h1 className='mt-4 text-5xl font-bold leading-tight'>Digitalizamos el comercio local, incluso para quienes nunca pudieron hacerlo.</h1><p className='mt-5 text-lg text-slate-600'>Conecta Local une tecnología SaaS y red operativa para que PYMES, revendedores y repartidores vendan más sin fricción.</p><div className='mt-8 flex flex-wrap gap-3'><Button size='lg'>Crear cuenta gratis</Button><Button variant='outline' size='lg'>Soy PYME</Button><Button variant='ghost' size='lg'>Soy Revendedor</Button></div></motion.div><motion.div initial={{opacity:0,scale:.98}} animate={{opacity:1,scale:1}} className='rounded-3xl border bg-gradient-to-br from-slate-900 to-blue-900 p-6 text-white shadow-2xl'><p className='font-semibold'>Panel inteligente Conecta IA</p><div className='mt-6 space-y-3'>{['24 clientes por contactar hoy','7 alertas de inventario críticas','3 promociones sugeridas por IA','+18% potencial de ventas semanal'].map(x=><div key={x} className='rounded-xl bg-white/10 p-3'>{x}</div>)}</div></motion.div></section>
<section className='border-y bg-white py-16'><div className='container grid gap-6 md:grid-cols-3'>{[['+500', 'negocios conectados'],['+2,000','entregas completadas'],['95%','satisfacción de usuarios']].map(([n,t])=><Card key={t} className='p-7 text-center'><p className='text-4xl font-bold text-blue-600'><CountUp end={Number(n.replace(/[^\d]/g,''))} duration={2} suffix={n.includes('%')?'%':'+'} /></p><p className='mt-2 text-slate-600'>{t}</p></Card>)}</div></section>
<section className='container py-20'><h2 className='section-title'>El problema que frenaba al comercio local</h2><div className='mt-10 grid gap-4 md:grid-cols-3'>{['Ventas limitadas','Procesos manuales','Falta de digitalización','Logística complicada','Poca visibilidad','Falta de clientes'].map(t=><Card key={t} className='p-6'><Store className='mb-4 text-blue-600'/><h3 className='font-semibold'>{t}</h3></Card>)}</div></section>
<section id='como-funciona' className='bg-slate-900 py-20 text-white'><div className='container'><h2 className='section-title !text-white'>No somos solo una app. Somos un ecosistema.</h2><div className='mt-10 grid gap-6 md:grid-cols-2'><Card className='border-white/20 bg-white/10 p-6 text-white'><h3 className='text-xl font-semibold'>Ecosistema SaaS empresarial</h3><p className='mt-3 text-slate-200'>CRM, inventario, pedidos, analítica y marketplace B2B para escalar PYMES digitales.</p></Card><Card className='border-white/20 bg-white/10 p-6 text-white'><h3 className='text-xl font-semibold'>Red operativa comercial</h3><p className='mt-3 text-slate-200'>Revendedores verificados y repartidores convierten negocios no digitalizados en ventas reales.</p></Card></div></div></section>
<section id='beneficios' className='container py-20'><h2 className='section-title'>Beneficios por perfil</h2><div className='mt-10 grid gap-5 md:grid-cols-4'>{[['PYMES',Users],['Revendedores',ShieldCheck],['Repartidores',Truck],['Clientes',Sparkles]].map(([n,I])=><Card key={String(n)} className='p-6'><I className='text-blue-600'/><h3 className='mt-3 font-semibold'>{String(n)}</h3><p className='mt-2 text-sm text-slate-600'>Más oportunidades, más ingresos y operaciones más simples con una sola plataforma.</p></Card>)}</div></section>
<section className='bg-white py-20'><div className='container'><h2 className='section-title'>Testimonios reales</h2><div className='mt-8 overflow-hidden' ref={emblaRef}><div className='flex gap-4'>{['Conecta Local duplicó nuestras ventas en 3 meses.','Ahora gestiono pedidos y entregas sin caos.','Como revendedora, tengo ingresos estables cada semana.'].map(t=><div key={t} className='min-w-0 flex-[0_0_100%] md:flex-[0_0_50%]'><Card className='h-full p-6'><p className='text-slate-700'>“{t}”</p></Card></div>)}</div></div></div></section>
<section id='faq' className='container py-20'><h2 className='section-title'>Preguntas frecuentes</h2><Accordion type='single' collapsible className='mt-8 w-full'>{[['¿Necesito experiencia tecnológica?','No. Diseñamos flujos simples y soporte guiado para que empieces rápido.'],['¿Qué hace un revendedor?','Representa negocios locales, gestiona catálogo, ventas y validación comercial.'],['¿Cómo validan negocios?','Con verificación documental, visitas y control de reputación operativa.'],['¿Tiene costo?','Puedes iniciar con plan gratuito y escalar según volumen.'],['¿Puedo gestionar entregas?','Sí, con red de repartidores y trazabilidad en tiempo real.']].map(([q,a])=><AccordionItem key={q} value={q}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent>{a}</AccordionContent></AccordionItem>)}</Accordion></section>
<section className='container pb-24'><Card className='bg-blue-600 p-10 text-center text-white'><h2 className='text-3xl font-bold'>Únete al futuro del comercio local</h2><p className='mt-3 text-blue-100'>Regístrate hoy y activa tu crecimiento con Conecta Local.</p><Button variant='outline' size='lg' className='mt-6 border-white bg-white text-blue-700 hover:bg-blue-50'>Registrarme ahora <ArrowRight className='ml-2 h-4 w-4' /></Button></Card></section>
</main>
<footer className='border-t bg-slate-950 py-10 text-slate-300'><div className='container flex flex-col justify-between gap-4 md:flex-row'><p>© 2026 Conecta Local. Todos los derechos reservados.</p><div className='flex gap-6 text-sm'><a href='#' className='hover:text-white'>Privacidad</a><a href='#' className='hover:text-white'>Términos</a><a href='#' className='hover:text-white'>Contacto</a></div></div></footer>
</div>}
