import { useState } from 'react'
import { motion } from 'framer-motion'
import CountUp from 'react-countup'
import useEmblaCarousel from 'embla-carousel-react'
import { ArrowRight, Bot, Boxes, ChartNoAxesCombined, Handshake, PackageSearch, ShieldCheck, Store, Truck, Users } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion'
import { navLinks, faqs } from '@/sections/data'

const rise = { hidden: { opacity: 0, y: 18 }, show: { opacity: 1, y: 0 } }

export default function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [emblaRef] = useEmblaCarousel({ loop: true })

  return <div id='inicio'>
    <header className='sticky top-0 z-50 border-b border-border/80 bg-background/95 backdrop-blur'><nav className='container-shell flex h-16 items-center justify-between'><a className='headline-md !text-[22px]' href='#inicio'>Péek</a><div className='hidden items-center gap-7 md:flex'>{navLinks.map(([label, href]) => <a key={label} href={href} className='text-sm text-on-surface-variant hover:text-foreground'>{label}</a>)}<Button>Registrarme</Button></div><Button variant='ghost' className='md:hidden' onClick={() => setMenuOpen(!menuOpen)}>Menú</Button></nav>{menuOpen && <div className='container-shell border-t py-3 md:hidden'>{navLinks.map(([label, href]) => <a key={label} href={href} className='block py-2'>{label}</a>)}<Button className='mt-2 w-full'>Registrarme</Button></div>}</header>
    <main>
      <section className='section-space container-shell grid items-center gap-10 md:grid-cols-2'><motion.div variants={rise} initial='hidden' animate='show'><span className='rounded-full bg-surface-soft px-3 py-1 text-xs font-semibold uppercase tracking-wide text-primary-dark'>Infraestructura de crecimiento local</span><h1 className='headline-lg mt-5 text-[44px] leading-[1.08] md:text-[58px]'>Reconectamos la economía local que el comercio digital dejó fuera.</h1><p className='muted-copy mt-5'>Péek conecta microempresas, intermediarios, logística y consumidores en un ecosistema B2B2C que transforma producción invisible en demanda real.</p><div className='mt-8 flex flex-wrap gap-3'><Button size='lg'>Únete ahora</Button><Button variant='outline' size='lg'>Ver cómo funciona</Button></div><div className='mt-8 grid grid-cols-3 gap-3'>{[['99%','unidades económicas son micro y pequeñas'],['52%','del PIB nace de ellas'],['+1', 'ecosistema híbrido integrado']].map(([n,t])=><div key={t} className='rounded-lg border border-border bg-surface p-3'><p className='headline-md text-primary'>{n}</p><p className='text-xs text-on-surface-variant'>{t}</p></div>)}</div></motion.div>
      <motion.div variants={rise} initial='hidden' animate='show' transition={{ delay: .15 }} className='rounded-xl border border-border bg-primary-dark p-6 text-white shadow-ambient'><p className='text-sm font-semibold text-primary-fixed'>Visión operativa en tiempo real</p><div className='mt-5 grid gap-3'>{['Productos con baja rotación: 18','Clientes por contactar hoy: 42','Promociones sugeridas por IA: 6','Oportunidades comerciales activas: 12'].map((x)=><div key={x} className='rounded-lg border border-white/15 bg-white/10 p-3 text-sm'>{x}</div>)}</div><div className='mt-5 rounded-lg border border-white/15 bg-white/5 p-4 text-sm'>Flujo activo: <strong>Productor → Intermediario → Cliente → Repartidor</strong></div></motion.div></section>

      <section className='container-shell pb-16'><div className='grid gap-4 md:grid-cols-3'>{[['+2,400','productos listos para conectar'],['+5.1M','microempresas potenciales en México'],['94%','de satisfacción en pilotos']].map(([n,t])=><Card key={t} className='p-6'><p className='headline-md text-primary'><CountUp end={Number(String(n).replace(/[^\d.]/g,''))} duration={2} suffix={String(n).includes('%')?'%':'+'} /></p><p className='muted-copy mt-1'>{t}</p></Card>)}</div></section>

      <section className='section-space bg-muted'><div className='container-shell'><h2 className='headline-lg'>La economía local produce más de lo que el mercado logra conectar.</h2><div className='mt-8 grid gap-4 md:grid-cols-3'>{[['Negocios invisibles',Store],['Procesos manuales',Boxes],['Logística fragmentada',Truck],['Baja digitalización',ChartNoAxesCombined],['Clientes inaccesibles',Users],['Oferta desconectada',PackageSearch]].map(([title,Icon])=><Card key={String(title)} className='p-5'><Icon className='text-primary'/><h3 className='mt-3 font-semibold'>{String(title)}</h3><p className='mt-2 text-sm text-on-surface-variant'>Sin infraestructura compartida, la producción regional pierde alcance y velocidad comercial.</p></Card>)}</div></div></section>

      <section id='como-funciona' className='section-space container-shell'><h2 className='headline-lg'>No obligamos a digitalizarse. Creamos infraestructura para incluir.</h2><p className='muted-copy mt-4 max-w-3xl'>Nuestro modelo híbrido conecta capacidades digitales con operación humana validada, para que cualquier negocio pueda vender.</p><div className='mt-8 grid gap-5 md:grid-cols-2'><Card id='negocios' className='p-6'><h3 className='headline-md'>Motor 1 — Ecosistema de crecimiento empresarial</h3><ul className='mt-4 space-y-2 text-sm text-on-surface-variant'><li>• CRM ligero y gestión de clientes</li><li>• Inventario, pedidos y analítica</li><li>• Marketplace B2B de proveedores</li><li>• Colaboración entre negocios y herramientas de crecimiento</li></ul></Card><Card id='intermediarios' className='p-6'><h3 className='headline-md'>Motor 2 — Red operativa de comercio</h3><ul className='mt-4 space-y-2 text-sm text-on-surface-variant'><li>• Socios Intermediarios validados</li><li>• Socios Repartidores para fulfillment</li><li>• Descubrimiento y compra para consumidores</li><li>• Inclusión comercial de negocios no digitalizados</li></ul></Card></div></section>

      <section id='beneficios' className='section-space bg-muted'><div className='container-shell'><h2 className='headline-lg'>Beneficios por actor del ecosistema</h2><div className='mt-8 grid gap-4 md:grid-cols-4'>{[['Productores / PYMES',Handshake],['Intermediarios',ShieldCheck],['Repartidores',Truck],['Consumidores',Users]].map(([n,I])=><Card key={String(n)} className='p-5'><I className='text-primary'/><h3 className='mt-3 font-semibold'>{String(n)}</h3><p className='mt-2 text-sm text-on-surface-variant'>Más ventas, mejor operación y mayor confianza en cada etapa del flujo comercial.</p></Card>)}</div></div></section>

      <section className='section-space container-shell'><h2 className='headline-lg'>¿Por qué Péek?</h2><div className='mt-8 grid gap-4 md:grid-cols-2'>{[['¿No sabes usar tecnología?','Te incorporamos con acompañamiento y operación asistida.'],['¿No tienes logística?','Activamos entrega mediante socios repartidores validados.'],['¿No tienes clientes digitales?','Nuestros intermediarios y canales te conectan con demanda real.'],['¿No puedes digitalizar tu negocio?','El ecosistema te integra sin exigir transformación inmediata.']].map(([q,a])=><Card key={q} className='p-6'><p className='font-semibold'>{q}</p><p className='mt-2 text-on-surface-variant'>{a}</p></Card>)}</div></section>

      <section className='section-space bg-primary-dark text-white'><div className='container-shell'><h2 className='headline-lg !text-white'>Asistente IA para decisiones comerciales accionables</h2><div className='mt-8 grid gap-6 md:grid-cols-2'><Card className='border-white/15 bg-white/5 p-6 text-white'><Bot className='text-secondary'/><p className='mt-3'>Prioriza clientes, detecta quiebres de inventario y recomienda promociones con impacto real en ventas.</p></Card><Card className='border-white/15 bg-white/5 p-6 text-white'><p className='text-sm text-white/80'>Dashboard IA</p><div className='mt-3 space-y-3 text-sm'>{['3 productos con rotación crítica','27 clientes de alto valor sin recompra','4 bundles sugeridos para esta semana'].map(x=><div key={x} className='rounded-md bg-white/10 p-3'>{x}</div>)}</div></Card></div></div></section>

      <section className='section-space container-shell'><h2 className='headline-lg'>Historias de crecimiento</h2><div className='mt-7 overflow-hidden' ref={emblaRef}><div className='flex gap-4'>{['Ahora vendemos en colonias donde nunca llegábamos.','Con Péek dejamos de trabajar a ciegas y empezamos a escalar.','Nuestra operación logística por fin está sincronizada con ventas.'].map(t=><div key={t} className='flex-[0_0_100%] md:flex-[0_0_50%]'><Card className='h-full p-6'><p>“{t}”</p></Card></div>)}</div></div></section>

      <section id='faq' className='section-space container-shell'><h2 className='headline-lg'>Preguntas frecuentes</h2><Accordion type='single' collapsible className='mt-6'>{faqs.map(([q,a])=><AccordionItem key={q} value={q}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent>{a}</AccordionContent></AccordionItem>)}</Accordion></section>

      <section className='container-shell pb-20'><Card className='bg-primary p-10 text-center text-white'><h2 className='headline-lg !text-white'>El futuro del comercio local no necesita esperar a que todos se digitalicen.</h2><p className='mt-3 text-white/90'>Únete a Péek y acelera el crecimiento de la economía productiva local.</p><Button size='lg' variant='outline' className='mt-6 border-white bg-white text-primary hover:bg-surface-soft'>Registrarme ahora <ArrowRight className='ml-2 h-4 w-4'/></Button></Card></section>
    </main>
  </div>
}
